org.gradle.daemon=true
org.gradle.parallel=true
# Turn the following on once you finished changing your settings/build:
# org.gradle.configuration-cache=true
# org.gradle.caching=true

# Plugin metadata used by settings.gradle.kts/build.gradle.kts
plugin_group=net.ofatech
plugin_name=ControlCore
plugin_description=ControlCore, a Hytale mod built to handle server-side configuration.
plugin_author_names=CaioMBA
plugin_author_emails=caiombaraujo@gmail.com
plugin_author_urls=https://github.com/CaioMBA
plugin_website=https://github.com/OFA-Tech/ControlCore-HytaleMod
server_version=*
plugin_main=net.ofatech.controlcore.ControlCore
# Optional Hytale location for the Assets.zip resolution:
# hytale.home_path=C:/Users/<you>/AppData/Roaming/Hytale
